### ISSUE TITLE
Does it work with iffical pi cam

### ISSUE THREAD

**Issue by cozmo14047** [BenVeghte/prusaconnect-webcam#1]
Hi there great script but could you modify it to use a pi camera if i run it on a pi. Thanks

**Comment by BenVeghte** [comment]
AsI think it should work. I don't have one of them to test it with, but if you do, the way you'd test the capability would be to run CameraTester.py and see if it took a photo.

**Comment by cozmo14047** [comment]
THank you i will try it in a bit

**Comment by BenVeghte** [comment]
Let me know how it turns out!

**Comment by cozmo14047** [comment]
> Let me know how it turns out!

Didint have time to test but is first priority tommorow

**Comment by BenVeghte** [comment]
Any luck?

**Comment by cozmo14047** [comment]
> Any luck?

my reply went to archives sorry about that. yes it works perfectly thank you

**Comment by BenVeghte** [comment]
Thanks for trying that out! I'll add that to the documentation in a bit.
